FROM ros:humble

# Install zsh
RUN apt-get update && apt-get install -y zsh && rm -rf /var/lib/apt/lists/*

# Install development tools and X11 libraries for GUI support
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    git \
    cmake \
    x11-apps \
    libgl1-mesa-glx \
    libx11-dev \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /workspace

# (Optional) Set zsh as the default shell
SHELL ["/bin/zsh", "-c"]

# Install Oh My Zsh and plugins
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended && \
    ZSH_CUSTOM=${ZSH_CUSTOM:-/root/.oh-my-zsh/custom} && \
    git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting && \
    git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git $ZSH_CUSTOM/plugins/fast-syntax-highlighting && \
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git $ZSH_CUSTOM/plugins/zsh-autocomplete && \
    sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting zsh-autocomplete)/' /root/.zshrc

# When running the container, mount your local directory with:
# docker run -it -v ~/projects/hoverboard_node:/workspace ros_humble_zsh

# To run GUI applications with X11 forwarding, use:
# xhost +local:docker
# docker run -it \
#   -e DISPLAY=$DISPLAY \
#   -v /tmp/.X11-unix:/tmp/.X11-unix \
#   -v ~/projects/hoverboard_node:/workspace \
#   ros_humble_zsh

